FROM gcr.io/sandbox-225221/python:trame-osmesa

# Create the /deploy directory with trame-user as the owner
RUN install -d -o trame-user -g trame-user /deploy

ENV TRAME_PARAVIEW=/opt/paraview

# Copy the server directory
COPY --chown=trame-user:trame-user ./server /deploy/server
